new

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -17,13 +17,14 @@ jobs:
         run: |
           apt-get update
           apt-get install -y rsync python3-pip
-          pip3 install --upgrade pip
-          pip3 install pytest
+          pip3 install --upgrade pip  # pipを最新にアップグレード
+          pip3 install pytest  # pytestをインストール
         shell: bash
 
       - name: Check pytest installation
         run: |
-          pytest --version || echo "pytest not found"
+          pip3 list  # インストールされたパッケージをリスト表示
+          pytest --version || echo "pytest not found"  # pytestのインストール確認
         shell: bash
 
       - name: Set up ROS 2 workspace
